
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-loop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: number-loop
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: number-loop
        image: ctazurereg.azurecr.io/number-loop:v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

