apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-redis-app
spec:
  selector:
    matchLabels:
      app: python-redis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-redis-app
    spec:
      containers:
        - name: python-redis-app
          image: mathiasregistry.azurecr.io/python-redis-app:v2
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: acr-auth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-reader-app
spec:
  selector:
    matchLabels:
      app: redis-reader-app
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-reader-app
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: python-redis-app
          image: mathiasregistry.azurecr.io/redis-reader-app:v3
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"


